### ISSUE TITLE
Not responsive 

### ISSUE THREAD

**Issue by Temian1** [izzanka/Luora#1]
Can you make it mobile friendly

**Comment by izzanka** [comment]
im sorry i dont have time to make it responsive

**Comment by Temian1** [comment]
> im sorry i dont have time to make it responsive

No worries will work on that, have you included the space

**Comment by izzanka** [comment]
well, im saw quora space was a bit complicated, and i think i will not adding another feature (notif, history etc) soon. Next update i'll just cleaning and refactor some codes.
